### ISSUE TITLE
Error 'runComets'

### ISSUE THREAD

**Issue by 2132030** [segrelab/comets#51]
I am using Linux system and MATLAB R2021b. 

runComets(layout,cometsDirectory)
Executing COMETS in the directory /home/name/CometsRunDir
Warning: Invalid file or directory '/usr/gurobi/gurobi1100/linux64/'. 
> In javaclasspath>local_validate_dynamic_path (line 271)
In javaclasspath>local_javapath (line 187)
In javaclasspath (line 103)
In runCometsOnDirectory (line 35)
In runComets (line 41) 

ans =

    '-script
     running script file: comets_script.txt
     Current Java version: 21.0.2
     Loading layout file 'comets_layout.txt'...
     null/COMETS_manifest.txt (No such file or directory)
     Unable to initialize manifest file. 
     Continuing without writing manifest file.
     Found 14 model files!
     Loading 'iYO844xml.txt' ...
     Exception in thread "main" java.lang.NoClassDefFoundError: gurobi/GRBException
     	at edu.bu.segrelab.comets.fba.FBAModel.<init>(FBAModel.java:224)
     	at edu.bu.segrelab.comets.fba.FBAModel.<init>(FBAModel.java:287)
     	at edu.bu.segrelab.comets.fba.FBAModel.loadModelFromFile(FBAModel.java:2648)
     	at edu.bu.segrelab.comets.fba.FBACometsLoader.loadModelFromFile(FBACometsLoader.java:2918)
     	at edu.bu.segrelab.comets.fba.FBACometsLoader.parseModelFileLine(FBACometsLoader.java:1168)
     	at edu.bu.segrelab.comets.fba.FBACometsLoader.loadLayoutFile(FBACometsLoader.java:316)
     	at edu.bu.segrelab.comets.Comets.loadLayoutFile(Comets.java:1657)
     	at edu.bu.segrelab.comets.Comets.runScript(Comets.java:541)
     	at edu.bu.segrelab.comets.Comets.<init>(Comets.java:233)
     	at edu.bu.segrelab.comets.Comets.main(Comets.java:2159)
     Caused by: java.lang.ClassNotFoundException: gurobi.GRBException
     	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
     	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
     	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
     	... 10 more

**Comment by dukovski** [comment]
Hi, 

It seems like you don't have Gurobi working properly. Did you get a license for Gurobi?

**Comment by 2132030** [comment]
yes, I got

**Comment by dukovski** [comment]
This conversation moved to cometspy, so should I close this issue?

**Comment by Ql-cy** [comment]
Hi, I got the same error. Did you solve it?

**Comment by dukovski** [comment]
> Hi, I got the same error. Did you solve it?

You need to have gurobi working properly, and have latest version of comets installed with latest version of gurobi. Try that and let me know if all ok.

**Comment by Ql-cy** [comment]
Hi&nbsp;dukovski,
&nbsp; &nbsp; My gurobi is the version 11. It might be the latest version. But I am not sure the comet-toolbox is the latest. Could you provide it for me? the matlab version.


Best,
Lu
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Jun 28, 2024 10:48 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [segrelab/comets] Error 'runComets' (Issue #51)

&nbsp;



  
Hi, I got the same error. Did you solve it?
  
You need to have gurobi working properly, and have latest version of comets installed with latest version of gurobi. Try that and let me know if all ok.

**Comment by dukovski** [comment]
We are behind with the Matlab toolbox development. Can you migrate to cometspy, the python toolbox/interface?

**Comment by Ql-cy** [comment]
Hi&nbsp;dukovski,
&nbsp; &nbsp; Since we usually use MATLAB, so we want to use the matlab toolbox. If there is no newer version of comets toolbox, could you please tell me the gurobi version that match current comets matlab toolbox?


Best,
Lu
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Jul 5, 2024 06:04 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [segrelab/comets] Error 'runComets' (Issue #51)

&nbsp;



 
We are behind with the Matlab toolbox development. Can you migrate to cometspy, the python toolbox/interface?
